# Force GitHub Actions re-scan
name: Deploy Oracle Portfolio 3.0

on:
  push:
    branches: [ staging ]
  workflow_dispatch:

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/staging'
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: functions/package-lock.json
          
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install Node.js dependencies
        run: |
          cd functions
          npm ci
          
      - name: Create and setup Python virtual environment
        run: |
          cd functions-python
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          echo "Python venv created and dependencies installed"
          ls -la venv/bin/
          
      - name: Deploy to Staging
        run: |
          cd functions-python
          echo "Activating Python virtual environment..."
          source venv/bin/activate
          echo "Python environment activated"
          cd ..
          echo "Deploying to Firebase..."
          firebase deploy --only functions:python --project oracle-portfolio-staging --token "$FIREBASE_TOKEN"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          ALPHA_VANTAGE_KEY: ${{ secrets.ALPHA_VANTAGE_KEY }}
          EIA_API_KEY: ${{ secrets.EIA_API_KEY }}
          FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
