name: Deploy Oracle Portfolio 3.0

on:
  push:
    branches:
      - staging
      - main
    paths:
      - 'functions-python/**'
  workflow_dispatch:

jobs:
  deploy-oracle-portfolio:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Create and Install Python Dependencies in venv
        run: |
          cd functions-python
          python3.10 -m venv venv  # Créer l'environnement virtuel (dans functions-python/venv)
          source venv/bin/activate # Activer l'environnement virtuel pour cette étape
          pip install --upgrade pip
          pip install -r requirements.txt
          deactivate # Désactiver après l'installation

      - name: Deploy to Staging
        if: github.ref == 'refs/heads/staging'
        run: firebase deploy --only functions:python --project oracle-portfolio-staging --token "${{ secrets.FIREBASE_TOKEN }}"
        # IMPORTANT : Pas de 'cd functions-python' ici. firebase deploy s'exécute depuis la racine du dépôt.

      - name: Deploy to Production
        if: github.ref == 'refs/heads/main'
        run: firebase deploy --only functions:python --project oracle-portfolio-prod --token "${{ secrets.FIREBASE_TOKEN }}"
        # IMPORTANT : Pas de 'cd functions-python' ici.

      - name: Health Check
        run: |
          if [ "${{ github.ref }}" == "refs/heads/staging" ]; then
            PROJECT="oracle-portfolio-staging"
          else
            PROJECT="oracle-portfolio-prod"
          fi
          echo "Testing Oracle Portfolio 3.0 health on $PROJECT..."
          curl -f "https://us-central1-$PROJECT.cloudfunctions.net/getSystemHealth" || exit 1
          echo "✅ Oracle Portfolio 3.0 deployed successfully!"
