name: Deploy Oracle Portfolio 3.0

on:
  push:
    branches:
      - staging
      - main
    paths:
      - 'functions-python/**'
  workflow_dispatch:

jobs:
  deploy-oracle-portfolio:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Install Python Dependencies
        run: |
          cd functions-python
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy to Staging
        if: github.ref == 'refs/heads/staging'
        run: firebase deploy --only functions:python --project oracle-portfolio-staging --token "${{ secrets.FIREBASE_TOKEN }}"

      - name: Deploy to Production
        if: github.ref == 'refs/heads/main'
        run: firebase deploy --only functions:python --project oracle-portfolio-prod --token "${{ secrets.FIREBASE_TOKEN }}"

      - name: Health Check
        run: |
          if [ "${{ github.ref }}" == "refs/heads/staging" ]; then
            PROJECT="oracle-portfolio-staging"
          else
            PROJECT="oracle-portfolio-prod"
          fi
          echo "Testing Oracle Portfolio 3.0 health on $PROJECT..."
          curl -f "https://us-central1-$PROJECT.cloudfunctions.net/getSystemHealth" || exit 1
          echo "✅ Oracle Portfolio 3.0 deployed successfully!"
